apiVersion: v1
kind: Pod
metadata:
  name: demo-k8s-pod
spec:
  volumes:
    - name: demo-pv-storage
      persistentVolumeClaim:
        claimName: demo-pv-claim
  containers:
    - name: demo-pv-container
      image: bapadua/k8s-demo:latest
      ports:
        - containerPort: 8081
          name: "demo-k8s-rest"
      volumeMounts:
        - mountPath: "/home"
          name: demo-pv-storage



